#!/bin/bash
gcc -E $CFILE -o c
#!/bin/bash
gcc -c $CFILE
#!/bin/bash
gcc -S $CFILE
#!/bin/bash
gcc $CFILE -o cisfun
# include <stdio.h>
/**
 * main - entry point
 * Return: Always 0 (success)
 */
int main(void)
{
/* Prints text to standard output*/
puts("\"Programming is like building a multilingual puzzle");
return (0);
}
#!/bin/bash
gcc -S -masm=intel $CFILE
#include <stdio.h>
#include <unistd.h>
/**
 * main - Prints exactly "and that piece of art is useful"
 * - Dora Korpar, 2015-10-19",
 *   followed by a new line, to the standard error.
 *   Return: Always 0 (Success)
 */
int main(void)
{
/* function that prints to standard output*/
write(2, "and that piece of art is useful\" - Dora Korpar, 2015-10-19\n", 59);
return (1);
}
